version: '2'
services:
#### NodeJS Container ####
    nodejs:
        image: node:6.9.5-alpine
        tty: true
        volumes:
            - ".:/usr/app"
#### RabbitMQ Container ####
    rabbitmq:
        image: rabbitmq:management-alpine
        tty: true
        ports:
            - "15672:15672"
            - "5672:5672"
            
#### Network เพื่อให้ Container สามารถคุยกันได้
# networks:
#     default:
#        external:
#            name: microservicenetwork

networks:
  network1:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450